//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylog.Shared.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daylog.Shared.Core.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error ocurred.
        /// </summary>
        public static string AnErrorOcurred {
            get {
                return ResourceManager.GetString("AnErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An unknown error ocurred.
        /// </summary>
        public static string AnUnknownErrorOcurred {
            get {
                return ResourceManager.GetString("AnUnknownErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A persistence error ocurred.
        /// </summary>
        public static string APersistenceErrorOcurred {
            get {
                return ResourceManager.GetString("APersistenceErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid credentials.
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A validation error ocurred.
        /// </summary>
        public static string AValidationErrorOcurred {
            get {
                return ResourceManager.GetString("AValidationErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company not exists: {0}.
        /// </summary>
        public static string Company_CompanyNotExists {
            get {
                return ResourceManager.GetString("Company_CompanyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name is required.
        /// </summary>
        public static string Company_NameIsRequired {
            get {
                return ResourceManager.GetString("Company_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name must be maximum {0} characters long.
        /// </summary>
        public static string Company_NameLengthTooLong {
            get {
                return ResourceManager.GetString("Company_NameLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is required.
        /// </summary>
        public static string CompanyUser_UserIsRequired {
            get {
                return ResourceManager.GetString("CompanyUser_UserIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data is null.
        /// </summary>
        public static string DataIsNull {
            get {
                return ResourceManager.GetString("DataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JWT Authorization header using the Bearer scheme. Enter &apos;Bearer&apos; [space] and then your token in the text input below..
        /// </summary>
        public static string Documentation_AuthenticationDescription {
            get {
                return ResourceManager.GetString("Documentation_AuthenticationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a API for Daylog, a daily logging application.
        /// </summary>
        public static string Documentation_InfoDescription {
            get {
                return ResourceManager.GetString("Documentation_InfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Daylog API.
        /// </summary>
        public static string Documentation_InfoTitle {
            get {
                return ResourceManager.GetString("Documentation_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create a new company.
        /// </summary>
        public static string Endpoint_CreateCompanyDescription {
            get {
                return ResourceManager.GetString("Endpoint_CreateCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create Company.
        /// </summary>
        public static string Endpoint_CreateCompanySummary {
            get {
                return ResourceManager.GetString("Endpoint_CreateCompanySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create a new user.
        /// </summary>
        public static string Endpoint_CreateUserDescription {
            get {
                return ResourceManager.GetString("Endpoint_CreateUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create User.
        /// </summary>
        public static string Endpoint_CreateUserSummary {
            get {
                return ResourceManager.GetString("Endpoint_CreateUserSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete a user by ID.
        /// </summary>
        public static string Endpoint_DeleteUserDescription {
            get {
                return ResourceManager.GetString("Endpoint_DeleteUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete User.
        /// </summary>
        public static string Endpoint_DeleteUserSummary {
            get {
                return ResourceManager.GetString("Endpoint_DeleteUserSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get a list of all companies.
        /// </summary>
        public static string Endpoint_GetCompaniesDescription {
            get {
                return ResourceManager.GetString("Endpoint_GetCompaniesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get Companies.
        /// </summary>
        public static string Endpoint_GetCompaniesSummary {
            get {
                return ResourceManager.GetString("Endpoint_GetCompaniesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get a user by ID.
        /// </summary>
        public static string Endpoint_GetUserDescription {
            get {
                return ResourceManager.GetString("Endpoint_GetUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get a list of all users.
        /// </summary>
        public static string Endpoint_GetUsersDescription {
            get {
                return ResourceManager.GetString("Endpoint_GetUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get a list of users with keyset pagination.
        /// </summary>
        public static string Endpoint_GetUsersKeysetPaginationDescription {
            get {
                return ResourceManager.GetString("Endpoint_GetUsersKeysetPaginationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get Users With Keyset Pagination.
        /// </summary>
        public static string Endpoint_GetUsersKeysetPaginationSummary {
            get {
                return ResourceManager.GetString("Endpoint_GetUsersKeysetPaginationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get a list of users with offset pagination.
        /// </summary>
        public static string Endpoint_GetUsersOffsetPaginationDescription {
            get {
                return ResourceManager.GetString("Endpoint_GetUsersOffsetPaginationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get Users With Offset Pagination.
        /// </summary>
        public static string Endpoint_GetUsersOffsetPaginationSummary {
            get {
                return ResourceManager.GetString("Endpoint_GetUsersOffsetPaginationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get Users.
        /// </summary>
        public static string Endpoint_GetUsersSummary {
            get {
                return ResourceManager.GetString("Endpoint_GetUsersSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get User.
        /// </summary>
        public static string Endpoint_GetUserSummary {
            get {
                return ResourceManager.GetString("Endpoint_GetUserSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login with credentials.
        /// </summary>
        public static string Endpoint_LoginDescription {
            get {
                return ResourceManager.GetString("Endpoint_LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        public static string Endpoint_LoginSummary {
            get {
                return ResourceManager.GetString("Endpoint_LoginSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Refresh tokens.
        /// </summary>
        public static string Endpoint_RefreshTokensDescription {
            get {
                return ResourceManager.GetString("Endpoint_RefreshTokensDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Refresh Tokens.
        /// </summary>
        public static string Endpoint_RefreshTokensSummary {
            get {
                return ResourceManager.GetString("Endpoint_RefreshTokensSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update an existing user by ID.
        /// </summary>
        public static string Endpoint_UpdateUserDescription {
            get {
                return ResourceManager.GetString("Endpoint_UpdateUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update User.
        /// </summary>
        public static string Endpoint_UpdateUserSummary {
            get {
                return ResourceManager.GetString("Endpoint_UpdateUserSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication.
        /// </summary>
        public static string EndpointTags_Authentication {
            get {
                return ResourceManager.GetString("EndpointTags_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Companies.
        /// </summary>
        public static string EndpointTags_Companies {
            get {
                return ResourceManager.GetString("EndpointTags_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Users.
        /// </summary>
        public static string EndpointTags_Users {
            get {
                return ResourceManager.GetString("EndpointTags_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If code is blank, errorType must be None, and vice versa.
        /// </summary>
        public static string IfCodeIsBlankErrorTypeMustBeNoneAndViceVersa {
            get {
                return ResourceManager.GetString("IfCodeIsBlankErrorTypeMustBeNoneAndViceVersa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The endpoint &apos;{0}&apos; ({1}.{2}) returns an invalid type. Results must encapsulate Result&lt;T&gt; where T implements IResponseDto.
        /// </summary>
        public static string InvalidEndpointReturnType {
            get {
                return ResourceManager.GetString("InvalidEndpointReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No errors.
        /// </summary>
        public static string NoErrors {
            get {
                return ResourceManager.GetString("NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more validation errors occurred.
        /// </summary>
        public static string OneOrMoreValidationErrorsOcurred {
            get {
                return ResourceManager.GetString("OneOrMoreValidationErrorsOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only the static None instance can be of type None.
        /// </summary>
        public static string OnlyStaticNoneInstanceCanBeOfTypeNone {
            get {
                return ResourceManager.GetString("OnlyStaticNoneInstanceCanBeOfTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only validation errors can be of type Validation.
        /// </summary>
        public static string OnlyValidationErrorsCanByOfTypeValidation {
            get {
                return ResourceManager.GetString("OnlyValidationErrorsCanByOfTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail is invalid.
        /// </summary>
        public static string User_EmailIsInvalid {
            get {
                return ResourceManager.GetString("User_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail is required.
        /// </summary>
        public static string User_EmailIsRequired {
            get {
                return ResourceManager.GetString("User_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail must be maximum {0} characters long.
        /// </summary>
        public static string User_EmailLengthTooLong {
            get {
                return ResourceManager.GetString("User_EmailLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name is required.
        /// </summary>
        public static string User_NameIsRequired {
            get {
                return ResourceManager.GetString("User_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name must be maximum {0} characters long.
        /// </summary>
        public static string User_NameLengthTooLong {
            get {
                return ResourceManager.GetString("User_NameLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password is required.
        /// </summary>
        public static string User_PasswordIsRequired {
            get {
                return ResourceManager.GetString("User_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must be maximum {0} characters long.
        /// </summary>
        public static string User_PasswordLengthTooLong {
            get {
                return ResourceManager.GetString("User_PasswordLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must be at least {0} characters long.
        /// </summary>
        public static string User_PasswordLengthTooShort {
            get {
                return ResourceManager.GetString("User_PasswordLengthTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profile is invalid.
        /// </summary>
        public static string User_ProfileIsInvalid {
            get {
                return ResourceManager.GetString("User_ProfileIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profile is required.
        /// </summary>
        public static string User_ProfileIsRequired {
            get {
                return ResourceManager.GetString("User_ProfileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Specified email is already in use.
        /// </summary>
        public static string User_SpecifiedEmailIsAlreadyInUse {
            get {
                return ResourceManager.GetString("User_SpecifiedEmailIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is not authorized to perform this action.
        /// </summary>
        public static string User_UserIsNotAuthorizedToPerformThisAction {
            get {
                return ResourceManager.GetString("User_UserIsNotAuthorizedToPerformThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is required.
        /// </summary>
        public static string User_UserIsRequired {
            get {
                return ResourceManager.GetString("User_UserIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not exists: {0}.
        /// </summary>
        public static string User_UserNotExists {
            get {
                return ResourceManager.GetString("User_UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not found.
        /// </summary>
        public static string User_UserNotFound {
            get {
                return ResourceManager.GetString("User_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User with id &apos;{0}&apos; is not authorized to perform this action.
        /// </summary>
        public static string User_UserWithIdIsNotAuthorizedToPerformThisAction {
            get {
                return ResourceManager.GetString("User_UserWithIdIsNotAuthorizedToPerformThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User with id &apos;{0}&apos; was not found.
        /// </summary>
        public static string User_UserWithIdWasNotFound {
            get {
                return ResourceManager.GetString("User_UserWithIdWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User with the specified email was not found.
        /// </summary>
        public static string User_UserWithSpecifiedEmailWasNotFound {
            get {
                return ResourceManager.GetString("User_UserWithSpecifiedEmailWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company is required.
        /// </summary>
        public static string UserCompany_CompanyIsRequired {
            get {
                return ResourceManager.GetString("UserCompany_CompanyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Administrator.
        /// </summary>
        public static string UserProfile_Admin {
            get {
                return ResourceManager.GetString("UserProfile_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Super administrator.
        /// </summary>
        public static string UserProfile_SuperAdmin {
            get {
                return ResourceManager.GetString("UserProfile_SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User.
        /// </summary>
        public static string UserProfile_User {
            get {
                return ResourceManager.GetString("UserProfile_User", resourceCulture);
            }
        }
    }
}
