//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylog.Application.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daylog.Application.Shared.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error ocurred.
        /// </summary>
        public static string AnErrorOcurred {
            get {
                return ResourceManager.GetString("AnErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An unknown error ocurred.
        /// </summary>
        public static string AnUnknownErrorOcurred {
            get {
                return ResourceManager.GetString("AnUnknownErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A persistence error ocurred.
        /// </summary>
        public static string APersistenceErrorOcurred {
            get {
                return ResourceManager.GetString("APersistenceErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A validation error ocurred.
        /// </summary>
        public static string AValidationErrorOcurred {
            get {
                return ResourceManager.GetString("AValidationErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data is null.
        /// </summary>
        public static string DataIsNull {
            get {
                return ResourceManager.GetString("DataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If code is blank, errorType must be None, and vice versa.
        /// </summary>
        public static string IfCodeIsBlankErrorTypeMustBeNoneAndViceVersa {
            get {
                return ResourceManager.GetString("IfCodeIsBlankErrorTypeMustBeNoneAndViceVersa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The endpoint &apos;{0}&apos; ({1}.{2}) returns an invalid type. Results must encapsulate Result&lt;T&gt; where T implements IResponseDto.
        /// </summary>
        public static string InvalidEndpointReturnType {
            get {
                return ResourceManager.GetString("InvalidEndpointReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No errors.
        /// </summary>
        public static string NoErrors {
            get {
                return ResourceManager.GetString("NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more validation errors occurred.
        /// </summary>
        public static string OneOrMoreValidationErrorsOcurred {
            get {
                return ResourceManager.GetString("OneOrMoreValidationErrorsOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only the static None instance can be of type None.
        /// </summary>
        public static string OnlyStaticNoneInstanceCanBeOfTypeNone {
            get {
                return ResourceManager.GetString("OnlyStaticNoneInstanceCanBeOfTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only validation errors can be of type Validation.
        /// </summary>
        public static string OnlyValidationErrorsCanByOfTypeValidation {
            get {
                return ResourceManager.GetString("OnlyValidationErrorsCanByOfTypeValidation", resourceCulture);
            }
        }
    }
}
